"""add candle_1m table

Revision ID: acf90ed6d39e
Revises: aedfc068b9c7
Create Date: 2026-03-16 21:40:15.081045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf90ed6d39e'
down_revision: Union[str, None] = 'aedfc068b9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candle_1m',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    op.create_index('ix_candle_1m_symbol_ts', 'candle_1m', ['symbol', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candle_1m_symbol_ts', table_name='candle_1m')
    op.drop_table('candle_1m')
    # ### end Alembic commands ###
