"""fix trade_journal: nullable trade_id, add entry_order_id

Revision ID: aedfc068b9c7
Revises: b6852b4bf0a0
Create Date: 2026-03-14 16:28:02.780186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aedfc068b9c7'
down_revision: Union[str, None] = 'b6852b4bf0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_journal', sa.Column('entry_order_id', sa.Integer(), nullable=True))
    op.alter_column('trade_journal', 'trade_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'trade_journal', 'orders', ['entry_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trade_journal', type_='foreignkey')
    op.alter_column('trade_journal', 'trade_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('trade_journal', 'entry_order_id')
    # ### end Alembic commands ###
