"""add trade_journal, onchain_scores, market_regime

Revision ID: b6852b4bf0a0
Revises: 
Create Date: 2026-03-14 15:57:42.303118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6852b4bf0a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onchain_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('funding_score', sa.Float(), nullable=True),
    sa.Column('oi_score', sa.Float(), nullable=True),
    sa.Column('whale_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onchain_symbol_ts', 'onchain_scores', ['symbol', 'computed_at'], unique=False)
    op.create_table('trade_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('market_regime', sa.String(length=20), nullable=False),
    sa.Column('entry_technical_scores', sa.JSON(), nullable=True),
    sa.Column('entry_mtf_scores', sa.JSON(), nullable=True),
    sa.Column('entry_sentiment_score', sa.Float(), nullable=False),
    sa.Column('entry_onchain_score', sa.Float(), nullable=True),
    sa.Column('entry_orderbook_imbalance', sa.Float(), nullable=True),
    sa.Column('entry_composite_score', sa.Float(), nullable=False),
    sa.Column('exit_technical_scores', sa.JSON(), nullable=True),
    sa.Column('exit_composite_score', sa.Float(), nullable=True),
    sa.Column('entry_reasoning', sa.Text(), nullable=False),
    sa.Column('exit_reasoning', sa.Text(), nullable=True),
    sa.Column('entry_chart_path', sa.String(length=255), nullable=True),
    sa.Column('exit_chart_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.alter_column('positions', 'direction',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'LONG'::character varying"))
    op.add_column('trades', sa.Column('market_regime', sa.String(length=20), nullable=True))
    op.alter_column('trades', 'direction',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'LONG'::character varying"))
    op.alter_column('trades', 'borrow_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'borrow_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('trades', 'direction',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'LONG'::character varying"))
    op.drop_column('trades', 'market_regime')
    op.alter_column('positions', 'direction',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'LONG'::character varying"))
    op.drop_table('trade_journal')
    op.drop_index('ix_onchain_symbol_ts', table_name='onchain_scores')
    op.drop_table('onchain_scores')
    # ### end Alembic commands ###
