"""SQLAlchemy ORM models for HellaCash."""
from __future__ import annotations

import enum
from datetime import datetime
from typing import Any, Dict, Optional

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


# ── Enums ─────────────────────────────────────────────────────────────────────


class Direction(str, enum.Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"


class OrderSide(str, enum.Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(str, enum.Enum):
    MARKET = "market"
    LIMIT = "limit"
    STOP_LIMIT = "stopLimit"


class OrderStatus(str, enum.Enum):
    NEW = "new"
    PARTIALLY_FILLED = "partiallyFilled"
    FILLED = "filled"
    CANCELED = "canceled"
    REJECTED = "rejected"


class ExitReason(str, enum.Enum):
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    SIGNAL = "signal"
    TRAILING_STOP = "trailing_stop"
    MANUAL = "manual"
    CIRCUIT_BREAKER = "circuit_breaker"


# ── Tables ────────────────────────────────────────────────────────────────────


class Asset(Base):
    """Tradeable pairs on Bitvavo."""

    __tablename__ = "assets"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    symbol: Mapped[str] = mapped_column(String(20), unique=True, nullable=False)
    base: Mapped[str] = mapped_column(String(10), nullable=False)
    quote: Mapped[str] = mapped_column(String(10), nullable=False)
    min_order_size: Mapped[float] = mapped_column(Float, default=0.0)
    price_precision: Mapped[int] = mapped_column(Integer, default=8)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class Candle(Base):
    """OHLCV candle data."""

    __tablename__ = "candles"
    __table_args__ = (
        UniqueConstraint("symbol", "interval", "timestamp", name="uq_candle"),
        Index("ix_candles_symbol_interval_ts", "symbol", "interval", "timestamp"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    interval: Mapped[str] = mapped_column(String(5), nullable=False)
    open: Mapped[float] = mapped_column(Float, nullable=False)
    high: Mapped[float] = mapped_column(Float, nullable=False)
    low: Mapped[float] = mapped_column(Float, nullable=False)
    close: Mapped[float] = mapped_column(Float, nullable=False)
    volume: Mapped[float] = mapped_column(Float, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class Signal(Base):
    """Every signal generated by the strategy engine."""

    __tablename__ = "signals"
    __table_args__ = (Index("ix_signals_symbol_ts", "symbol", "created_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    strategy_name: Mapped[str] = mapped_column(String(50), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    strength: Mapped[float] = mapped_column(Float, nullable=False)
    technical_score: Mapped[float] = mapped_column(Float, default=0.0)
    sentiment_score: Mapped[float] = mapped_column(Float, default=0.0)
    indicator_snapshot: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    acted_on: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class Order(Base):
    """Exchange order lifecycle."""

    __tablename__ = "orders"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    bitvavo_order_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, unique=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    side: Mapped[str] = mapped_column(String(5), nullable=False)
    order_type: Mapped[str] = mapped_column(String(20), nullable=False)
    status: Mapped[str] = mapped_column(String(20), default=OrderStatus.NEW)
    requested_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    fill_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    requested_amount: Mapped[float] = mapped_column(Float, nullable=False)
    filled_amount: Mapped[float] = mapped_column(Float, default=0.0)
    fee: Mapped[float] = mapped_column(Float, default=0.0)
    fee_currency: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    paper_trade: Mapped[bool] = mapped_column(Boolean, default=True)
    strategy_name: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    signal_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("signals.id"), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())


class Position(Base):
    """Currently open positions."""

    __tablename__ = "positions"
    __table_args__ = (UniqueConstraint("symbol", name="uq_position_symbol"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), default="LONG")  # LONG or SHORT
    strategy_name: Mapped[str] = mapped_column(String(50), nullable=False)
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    current_price: Mapped[float] = mapped_column(Float, nullable=False)
    quantity: Mapped[float] = mapped_column(Float, nullable=False)
    unrealized_pnl: Mapped[float] = mapped_column(Float, default=0.0)
    stop_loss_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    take_profit_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    trailing_stop_pct: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    highest_price: Mapped[float] = mapped_column(Float, nullable=False)  # for trailing stop (lowest for SHORT)
    entry_order_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("orders.id"), nullable=True)
    paper_trade: Mapped[bool] = mapped_column(Boolean, default=True)
    opened_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    last_updated: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())


class Trade(Base):
    """Closed round-trip trades (entry + exit paired)."""

    __tablename__ = "trades"
    __table_args__ = (Index("ix_trades_symbol_ts", "symbol", "created_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), default="LONG")  # LONG or SHORT
    strategy_name: Mapped[str] = mapped_column(String(50), nullable=False)
    entry_order_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("orders.id"), nullable=True)
    exit_order_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("orders.id"), nullable=True)
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    exit_price: Mapped[float] = mapped_column(Float, nullable=False)
    quantity: Mapped[float] = mapped_column(Float, nullable=False)
    gross_pnl: Mapped[float] = mapped_column(Float, nullable=False)
    net_pnl: Mapped[float] = mapped_column(Float, nullable=False)
    roi_pct: Mapped[float] = mapped_column(Float, nullable=False)
    entry_sentiment: Mapped[float] = mapped_column(Float, default=0.0)
    exit_sentiment: Mapped[float] = mapped_column(Float, default=0.0)
    hold_seconds: Mapped[int] = mapped_column(Integer, default=0)
    exit_reason: Mapped[str] = mapped_column(String(30), nullable=False)
    paper_trade: Mapped[bool] = mapped_column(Boolean, default=True)
    entry_features: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    borrow_fee: Mapped[float] = mapped_column(Float, default=0.0)  # short selling borrow cost
    market_regime: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class TradeJournal(Base):
    """Structured trade journal with auto-generated reasoning and chart refs."""
    __tablename__ = "trade_journal"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    trade_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("trades.id"), nullable=True, unique=True)
    entry_order_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("orders.id"), nullable=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    strategy_name: Mapped[str] = mapped_column(String(50), nullable=False)
    market_regime: Mapped[str] = mapped_column(String(20), nullable=False)
    entry_technical_scores: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    entry_mtf_scores: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    entry_sentiment_score: Mapped[float] = mapped_column(Float, default=0.0)
    entry_onchain_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    entry_orderbook_imbalance: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    entry_composite_score: Mapped[float] = mapped_column(Float, default=0.0)
    exit_technical_scores: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    exit_composite_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    entry_reasoning: Mapped[str] = mapped_column(Text, nullable=False)
    exit_reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    entry_chart_path: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    exit_chart_path: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class OnchainScore(Base):
    """Persisted on-chain metric scores for auditability."""
    __tablename__ = "onchain_scores"
    __table_args__ = (Index("ix_onchain_symbol_ts", "symbol", "computed_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    funding_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    oi_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    whale_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    composite_score: Mapped[float] = mapped_column(Float, nullable=False)
    raw_data: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    computed_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class PortfolioSnapshot(Base):
    """Periodic portfolio valuation (every 5 minutes)."""

    __tablename__ = "portfolio_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    total_equity_eur: Mapped[float] = mapped_column(Float, nullable=False)
    cash_eur: Mapped[float] = mapped_column(Float, nullable=False)
    positions_value_eur: Mapped[float] = mapped_column(Float, default=0.0)
    daily_pnl: Mapped[float] = mapped_column(Float, default=0.0)
    weekly_pnl: Mapped[float] = mapped_column(Float, default=0.0)
    max_drawdown_pct: Mapped[float] = mapped_column(Float, default=0.0)
    sharpe_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    win_rate: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    snapshot_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class SentimentScore(Base):
    """Aggregated sentiment scores per asset."""

    __tablename__ = "sentiment_scores"
    __table_args__ = (Index("ix_sentiment_symbol_ts", "symbol", "computed_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    source: Mapped[str] = mapped_column(String(20), nullable=False)  # reddit/twitter/news/aggregate
    score: Mapped[float] = mapped_column(Float, nullable=False)      # -1.0 to +1.0
    confidence: Mapped[float] = mapped_column(Float, default=0.5)
    post_count: Mapped[int] = mapped_column(Integer, default=0)
    sample_texts: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    computed_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class StrategyParams(Base):
    """Learnable strategy configuration (tuned by optimizer)."""

    __tablename__ = "strategy_params"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    strategy_name: Mapped[str] = mapped_column(String(50), unique=True, nullable=False)
    params: Mapped[Dict[str, Any]] = mapped_column(JSON, nullable=False)
    performance_score: Mapped[float] = mapped_column(Float, default=0.0)
    last_optimized_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    version: Mapped[int] = mapped_column(Integer, default=1)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())


class LearningEvent(Base):
    """Labeled training data for the adaptive learning system."""

    __tablename__ = "learning_events"
    __table_args__ = (Index("ix_learning_strategy_ts", "strategy_name", "recorded_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    trade_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("trades.id"), nullable=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    strategy_name: Mapped[str] = mapped_column(String(50), nullable=False)
    feature_vector: Mapped[Dict[str, Any]] = mapped_column(JSON, nullable=False)
    outcome: Mapped[int] = mapped_column(Integer, nullable=False)  # 1=win, 0=loss
    predicted_outcome: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    model_version: Mapped[int] = mapped_column(Integer, default=1)
    recorded_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
